[versions]
agp = "8.5.1"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.9.3"
constraintlayout = "2.1.4"
playServicesLocation = "21.0.1"
tens = "2.12.0"
litertSupportApi = "0.4.3"
lottieVersion = "3.4.0"
okhttpVersion ="4.9.3"
firebasePerfKtx = "21.0.4"
constraintlayoutVersion = "2.1.4"
androidxConstraintlayout = "2.2.1"
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
gms-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
tensorflow = {group="org.tensorflow",name="tensorflow-lite",version.ref="tens"}
litert-support-api = { group = "org.tensorflow", name = "tensorflow-lite-support", version.ref = "litertSupportApi" }
lottie = {group="com.airbnb.android",name="lottie",version.ref = "lottieVersion"}
okhttp = {group="com.squareup.okhttp3",name="okhttp",version.ref="okhttpVersion"}
firebase-perf-ktx = { group = "com.google.firebase", name = "firebase-perf-ktx", version.ref = "firebasePerfKtx" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }



